### ISSUE TITLE
Trouble to build for ` no field or method errors` in cel-go

### ISSUE THREAD

**Issue by emahiro** [bufbuild/protovalidate-go#30] opened 2023-08-18 17:32 UTC
## Description

I'm using protovalidate-go, but I found than I can't build my project using this library.

If there are solutions of this trouble, I want to know them.

## Expected Behavior

Success to build.

## Actual Behavior

Failed to build with `entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)` errors in cel-go.

## Screenshots/Logs

```sh
# github.com/google/cel-go/common/debug
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/debug/debug.go:173:13: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/debug/debug.go:197:13: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
# github.com/google/cel-go/parser
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:125:4: unknown field OptionalIndices in struct literal of type expr.Expr_CreateList
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:142:3: unknown field OptionalEntry in struct literal of type expr.Expr_CreateStruct_Entry
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:162:3: unknown field OptionalEntry in struct literal of type expr.Expr_CreateStruct_Entry
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:263:6: unknown field OptionalIndices in struct literal of type expr.Expr_CreateList
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/helper.go:263:32: listExpr.GetOptionalIndices undefined (type *expr.Expr_CreateList has no field or method GetOptionalIndices)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/unparser.go:310:24: l.GetOptionalIndices undefined (type *expr.Expr_CreateList has no field or method GetOptionalIndices)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/unparser.go:378:12: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/parser/unparser.go:402:12: entry.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
# github.com/google/cel-go/common/ast
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/ast/expr.go:509:34: l.ToExpr().GetListExpr().GetOptionalIndices undefined (type *expr.Expr_CreateList has no field or method GetOptionalIndices)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/ast/expr.go:527:13: e.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
../../../../go/pkg/mod/github.com/google/cel-go@v0.17.1/common/ast/expr.go:588:13: f.GetOptionalEntry undefined (type *expr.Expr_CreateStruct_Entry has no field or method GetOptionalEntry)
```

## Environment

- protovalidate-go v0.2.1
- go v1.21.0
- github.com/google/cel-go v0.17.1
- connect-go@v1.8.0

## Additional Context

I created an issue(https://github.com/google/cel-go/issues/811) in cel-go project first.
There are some sample code in this issue comments.

**Comment by elliotmjackson** [comment] 2023-08-22 14:17
Hi @emahiro, I'm going to look into this for you and see if i can come up with a solution for you.

**Comment by elliotmjackson** [comment] 2023-08-22 16:43
@emahiro, the provided information in these issues isn't sufficient to make a definitive determination of the exact problem. Therefore, I've taken the liberty of setting up a [demo project](https://github.com/elliotmjackson/protovalidate-demo/tree/ejackson/tcn-2306-protovalidate-go30-trouble-to-build-for-no-field-or-method) for your reference. In this project, you can observe everything functioning as expected. While I wasn't able to reproduce the problem you mentioned, I hope that by comparing your local version with my functional version, you can isolate and identify the issue more effectively.

**Comment by emahiro** [comment] 2023-08-23 09:47
@elliotmjackson 
Thank you for preparing the demo project!
I'll try it soon.

**Comment by elliotmjackson** [comment] 2023-08-23 16:21
no problem, given I cant replicate the issue im going to close this issue - if you need further support feel free to open another issue or [connect with us in our slack](https://buf.build/links/slack)

**Closed by elliotmjackson** 2023-08-23 16:21 UTC
Labels: Bug

**Comment by emahiro** [comment] 2023-08-23 16:58
@elliotmjackson 

I was able to fix my errors.
I used old dd-trace-go(datadog tracing library) which version is `v1.51.0` and this caused errors I found.
When I update them to latest version, the ast errors all fixed.

Thank you your kind support.

**Comment by mishabhi** [comment] 2024-02-16 15:17
> @elliotmjackson
> 
> I was able to fix my errors. I used old dd-trace-go(datadog tracing library) which version is `v1.51.0` and this caused errors I found. When I update them to latest version, the ast errors all fixed.
> 
> Thank you your kind support.

@elliotmjackson Would you mind sharing a bit of information how did you get to the root cause? I am facing the same issue and for me its a showstopper.

**Comment by emcfarlane** [comment] 2024-02-16 20:21
@mishabhi could you provide a bit more information about your current dependencies? I suspect it's a similar dependency issue. Could you include the relative go.mod versions.
