### ISSUE TITLE
[BUG] *.pb.validate.go Validate AND ValidateAll cannot use. 

### ISSUE THREAD

**Issue by FocusHuang** [bufbuild/protovalidate-go#93] opened 2024-01-20 09:35 UTC
## Description

when i use - plugin: buf.build/bufbuild/validate-go to generate validation, a *.pb.validate.go is generated, but no validation rule in function Validate or ValidateAll. if i want to use validate, i need to new a protovalidateor to validate the struct. is it excessive?

## Steps to Reproduce

buf.gen.yaml
```yaml
version: v1
managed:
  enabled: false
plugins:
  # generate go struct code
  - plugin: buf.build/protocolbuffers/go
    out: .
    opt:
      - paths=source_relative
  # generate message validator code
  - plugin: buf.build/bufbuild/validate-go
    out: .
    opt:
      - paths=source_relative
```
```protobuf
message Task {
  int64 id = 1;
  string name = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {min_len: 1}
  ];
  string description = 3 [
    (buf.validate.field).ignore_empty = true,
    (buf.validate.field).string = {min_len: 1}
  ];
}
```
task.pb.validate.go
```go
// Validate checks the field values on Task with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Task) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Task with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TaskMultiError, or nil if none found.
func (m *Task) ValidateAll() error {
	return m.validate(true)
}

func (m *Task) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Description

	if len(errors) > 0 {
		return TaskMultiError(errors)
	}

	return nil
}
```

## Expected Behavior

i can use task.Validate() or task.ValidateAll() to validate fields

## Actual Behavior

all pass directly

## Environment

- **Operating System**: Linux
- **Version**: Ubuntu 22.04
- **Compiler/Toolchain**:  Buf
- **Protobuf Compiler & Version**: 
- **Protoc-gen-validate Version**:  
- **Protovalidate Version**:  e097f827e65240ac9fd4b1158849a8fc
- **BufVersion**: 1.28.1

**Comment by nicksnyder** [comment] 2024-01-22 17:12
Hi @FocusHuang, the `buf.build/bufbuild/validate-go` plugin is for [`protoc-gen-validate`](https://github.com/bufbuild/protoc-gen-validate) which is a different project.

`protovalidate` (this project) does not require any code generation. You can look at the [README](https://github.com/bufbuild/protovalidate-go?tab=readme-ov-file#example) for an example on how to perform validation.

Duplicate of https://github.com/bufbuild/protovalidate-go/issues/67#issuecomment-1785844721

**Closed by nicksnyder** 2024-01-22 17:12 UTC
Labels: Bug

**Comment by Panlq** [comment] 2024-02-22 07:25
Why was the code generation function of protoc-gen-validate abandoned? @nicksnyder

**Comment by rodaine** [comment] 2024-02-22 17:11
Hi @Panlq! We covered the impetus for moving to a non-codegen approach in our [blog post](https://buf.build/blog/protoc-gen-validate-v1-and-v2/) announcing the protovalidate project.
